# Generated by Django 5.0.2 on 2024-02-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='ano',
            field=models.IntegerField(default=2024),
        ),
    ]
