# Generated by Django 5.0.2 on 2024-02-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_animal_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='ano',
            field=models.IntegerField(default=2000),
        ),
    ]
