# Generated by Django 5.0.2 on 2024-02-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_animal_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='raca',
            field=models.CharField(default='Raça não Identificada', max_length=60),
        ),
        migrations.AlterField(
            model_name='animal',
            name='ano',
            field=models.IntegerField(default=2000),
        ),
    ]
