# Generated by Django 5.0.2 on 2024-02-27 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('ano_fundacao', models.PositiveIntegerField()),
                ('divisao', models.CharField(choices=[('A', 'Série A'), ('B', 'Série B'), ('C', 'Série C'), ('D', 'Série D'), ('S', 'Sem Série')], default='S', max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Clube',
                'verbose_name_plural': 'Clube',
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('numero_camisa', models.PositiveIntegerField()),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futebol.clube')),
            ],
            options={
                'verbose_name_plural': 'Jogadores',
            },
        ),
    ]
