# Generated by Django 5.0.2 on 2024-02-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clube',
            options={'verbose_name': 'Clube', 'verbose_name_plural': 'Clubes'},
        ),
        migrations.AddField(
            model_name='clube',
            name='escudo',
            field=models.ImageField(blank=True, null=True, upload_to='escudos'),
        ),
        migrations.AlterField(
            model_name='clube',
            name='ano_fundacao',
            field=models.PositiveIntegerField(help_text='Ano que o Clube foi criado'),
        ),
    ]
