# Generated by Django 5.0.2 on 2024-02-28 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicos', '0001_initial'),
        ('futebol', '0002_alter_clube_options_clube_escudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicos.cidade'),
        ),
        migrations.AlterField(
            model_name='clube',
            name='ano_fundacao',
            field=models.PositiveIntegerField(help_text='Ano que o Clube foi criado', verbose_name='Ano Fundação'),
        ),
        migrations.AlterField(
            model_name='clube',
            name='divisao',
            field=models.CharField(choices=[('A', 'Série A'), ('B', 'Série B'), ('C', 'Série C'), ('D', 'Série D'), ('S', 'Sem Série')], default='S', max_length=64, null=True, verbose_name='Divisão'),
        ),
    ]
