# Generated by Django 5.0.2 on 2024-02-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0003_clube_cidade_alter_clube_ano_fundacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='modalidade',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='F', max_length=2),
        ),
    ]
