# Generated by Django 5.0.2 on 2024-02-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=120, verbose_name='Descrição'),
        ),
    ]
