# Generated by Django 5.0.2 on 2024-02-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_produto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(null=True, upload_to='imagens_produtos'),
        ),
    ]
