# Generated by Django 5.0.2 on 2024-02-20 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_categoria_produto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='catalogo.produto')),
            ],
        ),
    ]
