# Generated by Django 5.0.2 on 2024-02-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='sigla',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
